# Generated by Django 5.2.8 on 2025-11-18 13:59

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_code',
            field=models.CharField(blank=True, default=users.models.generate_unique_code, max_length=10, null=True),
        ),
    ]
