# Generated by Django 5.2.8 on 2025-11-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
