# Generated by Django 5.2.8 on 2025-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='repeats',
            field=models.IntegerField(default=1),
        ),
    ]
